-- =====================================================================
-- SmartSpender - V2 Seed test data
--
-- Creates one demo user with 15 categories and ~250 transactions
-- spanning 2023-2026, including edge cases:
--   * Very long name (150 chars) and long category name (80 chars)
--   * Unicode / emoji in transaction names
--   * Zero-category transactions on old dates (now enforced NOT NULL)
--   * Large amounts ($1,000,000 refund)
--
-- Idempotent: uses ON CONFLICT DO NOTHING so re-running is safe if the
-- history table is ever cleared.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Test user
--
-- Password: hunter2hunter2
-- Hash: BCrypt cost 10, generated by BCryptPasswordEncoder.
-- Regenerate with:
--   mvn -q compile exec:java "-Dexec.mainClass=com.smartspender.util.GenerateHash" "-Dexec.args=hunter2hunter2"
-- ---------------------------------------------------------------------
INSERT INTO users (email, password_hash, display_name, currency_pref, email_verified)
VALUES (
    'smartspender@test.local',
    '$2a$10$nANRSGu4NW1JELcQKz41yutD815ZMLP2HmgkM83f4D.BlyQlm1/iy',
    'Smart Spender',
    'USD',
    TRUE
);

-- ---------------------------------------------------------------------
-- 2. Categories (15)
--    Colors are deliberately distinct hex values, all unique per user.
-- ---------------------------------------------------------------------
INSERT INTO categories (user_id, name, icon, color, is_default) VALUES
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'), 'Groceries',           'pi pi-shopping-cart', '#22c55e', TRUE),
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'), 'School Supplies',     'pi pi-book',          '#3b82f6', TRUE),
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'), 'Rent',                'pi pi-home',          '#ef4444', TRUE),
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'), 'Insurance',           'pi pi-shield',        '#8b5cf6', TRUE),
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'), 'Hygiene Products',    'pi pi-sparkles',      '#14b8a6', TRUE),
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'), 'Medical Expenses',    'pi pi-heart',         '#ec4899', TRUE),
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'), 'Dental Expenses',     'pi pi-heart-fill',    '#f472b6', TRUE),
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'), 'Optometry Expenses',  'pi pi-eye',           '#06b6d4', TRUE),
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'), 'Pet Expenses',        'pi pi-heart',         '#f59e0b', TRUE),
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'), 'Car Expense',         'pi pi-car',           '#64748b', TRUE),
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'), 'Eat Out',             'pi pi-star',          '#f97316', TRUE),
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'), 'Snack',               'pi pi-apple',         '#eab308', TRUE),
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'), 'Clothes',             'pi pi-shopping-bag',  '#a855f7', TRUE),
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'), 'Cosmetics',           'pi pi-briefcase',     '#d946ef', TRUE),
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'), 'Household Supplies',  'pi pi-bell',          '#0ea5e9', TRUE);

-- ---------------------------------------------------------------------
-- 3. Transactions — 4 years of semi-realistic data
--
-- Strategy: cross join categories with a date series, add randomness.
-- This produces roughly 15 categories × 24 periods × ~0.7 probability
-- ≈ 250 rows. Amounts are randomized within category-appropriate ranges.
-- ---------------------------------------------------------------------

-- Helper: a stable pseudo-random seed so re-running produces the same rows
-- (setseed affects the whole session; use carefully)
SELECT setseed(0.42);

-- Build a temp mapping of category → min/max amount for realistic values
CREATE TEMP TABLE category_amounts (
    category_name VARCHAR(80) PRIMARY KEY,
    amount_min    NUMERIC(14,2),
    amount_max    NUMERIC(14,2),
    monthly_freq  INTEGER  -- expected number of transactions per month
) ON COMMIT DROP;

INSERT INTO category_amounts VALUES
    ('Groceries',           30.00,  180.00,  4),
    ('School Supplies',      5.00,   80.00,  1),
    ('Rent',              1400.00, 1600.00,  1),
    ('Insurance',           80.00,  220.00,  1),
    ('Hygiene Products',     5.00,   45.00,  2),
    ('Medical Expenses',    20.00,  350.00,  1),
    ('Dental Expenses',     80.00,  400.00,  1),
    ('Optometry Expenses',  60.00,  250.00,  1),
    ('Pet Expenses',        15.00,  120.00,  2),
    ('Car Expense',         40.00,  400.00,  2),
    ('Eat Out',             15.00,  120.00,  6),
    ('Snack',                2.00,   20.00,  8),
    ('Clothes',             25.00,  200.00,  2),
    ('Cosmetics',           10.00,   90.00,  1),
    ('Household Supplies',  10.00,   80.00,  2);

-- ---------------------------------------------------------------------
-- 3a. Generate transactions for the last 4 years
--     Income: one salary per month, plus sporadic refunds
--     Expenses: many rows per month based on monthly_freq
-- ---------------------------------------------------------------------

-- Expense rows
INSERT INTO transactions (user_id, category_id, amount, type, name, notes, txn_date)
SELECT
    u.id,
    c.id,
    -- random amount in the category's range, rounded to 2 decimals
    ROUND((ca.amount_min + random() * (ca.amount_max - ca.amount_min))::numeric, 2),
    'EXPENSE',
    -- sample merchants per category with a fallback
    CASE c.name
        WHEN 'Groceries'          THEN (ARRAY['Loblaws','Metro','No Frills','Costco','FreshCo'])[floor(random()*5)+1]
        WHEN 'School Supplies'    THEN (ARRAY['Staples','Amazon','Indigo','Dollarama'])[floor(random()*4)+1]
        WHEN 'Rent'               THEN 'Landlord'
        WHEN 'Insurance'          THEN (ARRAY['TD Insurance','RBC Insurance','Sun Life'])[floor(random()*3)+1]
        WHEN 'Hygiene Products'   THEN (ARRAY['Shoppers Drug Mart','Walmart','Amazon'])[floor(random()*3)+1]
        WHEN 'Medical Expenses'   THEN (ARRAY['Walk-In Clinic','Pharmacy','Hospital'])[floor(random()*3)+1]
        WHEN 'Dental Expenses'    THEN 'Dental Clinic'
        WHEN 'Optometry Expenses' THEN 'Optometrist'
        WHEN 'Pet Expenses'       THEN (ARRAY['PetSmart','Vet Clinic','Pet Valu'])[floor(random()*3)+1]
        WHEN 'Car Expense'        THEN (ARRAY['Shell','Petro-Canada','Canadian Tire','Jiffy Lube'])[floor(random()*4)+1]
        WHEN 'Eat Out'            THEN (ARRAY['Tim Hortons','Starbucks','McDonalds','Local Restaurant','Sushi Place'])[floor(random()*5)+1]
        WHEN 'Snack'              THEN (ARRAY['Tim Hortons','Vending Machine','Corner Store'])[floor(random()*3)+1]
        WHEN 'Clothes'            THEN (ARRAY['H&M','Zara','Uniqlo','Winners'])[floor(random()*4)+1]
        WHEN 'Cosmetics'          THEN (ARRAY['Sephora','Shoppers','Ulta'])[floor(random()*3)+1]
        WHEN 'Household Supplies' THEN (ARRAY['Canadian Tire','IKEA','Walmart'])[floor(random()*3)+1]
        ELSE 'Store'
    END,
    NULL,
    -- random date in the period, weighted toward mid-month
    (CURRENT_DATE - (random() * 365 * 4)::integer)::date
FROM users u
CROSS JOIN categories c
JOIN category_amounts ca ON ca.category_name = c.name
CROSS JOIN generate_series(0, 47) AS period_idx  -- 48 months = 4 years
CROSS JOIN generate_series(1, 4) AS j            -- up to 4 slots per category per month
WHERE u.email = 'smartspender@test.local'
  AND random() < (ca.monthly_freq::float / 4.0);  -- probability per slot

-- Income rows: monthly salary
INSERT INTO transactions (user_id, category_id, amount, type, name, notes, txn_date)
SELECT
    u.id,
    (SELECT id FROM categories WHERE user_id = u.id AND name = 'Groceries' LIMIT 1),  -- placeholder category
    3200.00 + ROUND((random() * 400)::numeric, 2),
    'INCOME',
    'Monthly Salary',
    'Direct deposit',
    (date_trunc('month', CURRENT_DATE) - (m || ' months')::interval)::date + 14
FROM users u
CROSS JOIN generate_series(0, 47) AS m
WHERE u.email = 'smartspender@test.local';

-- A handful of income "refunds"
INSERT INTO transactions (user_id, category_id, amount, type, name, notes, txn_date)
VALUES
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'),
     (SELECT id FROM categories WHERE user_id = (SELECT id FROM users WHERE email = 'smartspender@test.local') AND name = 'Groceries'),
     1000000.00, 'INCOME', 'Class-action refund (groceries)', 'Edge case: large amount', '2024-06-15'),
    ((SELECT id FROM users WHERE email = 'smartspender@test.local'),
     (SELECT id FROM categories WHERE user_id = (SELECT id FROM users WHERE email = 'smartspender@test.local') AND name = 'Car Expense'),
     1200.00, 'INCOME', 'Insurance payout', 'After fender bender', '2025-03-22');

-- ---------------------------------------------------------------------
-- 4. Edge cases
-- ---------------------------------------------------------------------

-- 4a. Very long transaction name (150 chars — the column max)
INSERT INTO transactions (user_id, category_id, amount, type, name, notes, txn_date)
SELECT
    u.id,
    c.id,
    45.00,
    'EXPENSE',
    RPAD('Extremely long merchant name for layout testing — ', 150, 'x'),
    'This row tests the 150-char limit and text truncation',
    '2026-06-15'
FROM users u
JOIN categories c ON c.user_id = u.id AND c.name = 'Groceries'
WHERE u.email = 'smartspender@test.local';

-- 4b. Very long category name (80 chars — the column max)
INSERT INTO categories (user_id, name, icon, color, is_default)
VALUES (
    (SELECT id FROM users WHERE email = 'smartspender@test.local'),
    RPAD('Super Long Category Name For Layout Testing ', 80, '.'),
    'pi pi-tag',
    '#78716c',
    FALSE
);

INSERT INTO transactions (user_id, category_id, amount, type, name, notes, txn_date)
SELECT
    u.id,
    c.id,
    25.00,
    'EXPENSE',
    'Edge case — long category',
    NULL,
    '2026-05-10'
FROM users u
JOIN categories c ON c.user_id = u.id AND c.name LIKE 'Super Long%'
WHERE u.email = 'smartspender@test.local';

-- 4c. Unicode / emoji in transaction name
INSERT INTO transactions (user_id, category_id, amount, type, name, notes, txn_date)
SELECT
    u.id,
    c.id,
    89.99,
    'EXPENSE',
    'Café René ☕ — emoji & accents',
    'Tests UTF-8 rendering',
    '2026-04-20'
FROM users u
JOIN categories c ON c.user_id = u.id AND c.name = 'Eat Out'
WHERE u.email = 'smartspender@test.local';

-- 4d. Notes containing a lot of text
INSERT INTO transactions (user_id, category_id, amount, type, name, notes, txn_date)
SELECT
    u.id,
    c.id,
    150.00,
    'EXPENSE',
    'Long notes test',
    RPAD('Lorem ipsum dolor sit amet. ', 500, 'more text '),
    '2026-03-12'
FROM users u
JOIN categories c ON c.user_id = u.id AND c.name = 'Clothes'
WHERE u.email = 'smartspender@test.local';

-- 4e. Very small amount
INSERT INTO transactions (user_id, category_id, amount, type, name, notes, txn_date)
SELECT u.id, c.id, 0.01, 'EXPENSE', 'Penny', NULL, '2026-02-14'
FROM users u
JOIN categories c ON c.user_id = u.id AND c.name = 'Snack'
WHERE u.email = 'smartspender@test.local';

-- 4f. Large amount
INSERT INTO transactions (user_id, category_id, amount, type, name, notes, txn_date)
SELECT u.id, c.id, 99999.99, 'EXPENSE', 'Large one-time purchase', NULL, '2026-01-05'
FROM users u
JOIN categories c ON c.user_id = u.id AND c.name = 'Household Supplies'
WHERE u.email = 'smartspender@test.local';

-- ---------------------------------------------------------------------
-- 5. Budgets — most recent month, a few categories
-- ---------------------------------------------------------------------

INSERT INTO budgets (user_id, category_id, limit_amount, month, year)
SELECT
    u.id,
    c.id,
    CASE c.name
        WHEN 'Groceries'          THEN 500.00
        WHEN 'Eat Out'            THEN 300.00
        WHEN 'Snack'              THEN 100.00
        WHEN 'Car Expense'        THEN 250.00
        WHEN 'Hygiene Products'   THEN 80.00
        WHEN 'Pet Expenses'       THEN 150.00
        ELSE NULL
    END,
    EXTRACT(MONTH FROM CURRENT_DATE)::smallint,
    EXTRACT(YEAR FROM CURRENT_DATE)::smallint
FROM users u
JOIN categories c ON c.user_id = u.id
WHERE u.email = 'smartspender@test.local'
  AND c.name IN ('Groceries','Eat Out','Snack','Car Expense','Hygiene Products','Pet Expenses');
